# Runs weekly or after every push to all branches to validate indexing against development environment

trigger:
  branches:
    include: ["main", "*"]
  paths:
    exclude: ["doc", "*.md"]

queue:
  name: Hosted VS2017
  timeoutInMinutes: 60

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- task: MS-RichCodeNav.Indexer.build-task.RichCodeNavIndexer@0.1
  displayName: Rich Code Navigation Upload to Development
  inputs:
    languages: 'typescript'
    githubServiceConnection: 'noellelc'
    environment: development
    nugetFeed: 'https://devdiv.pkgs.visualstudio.com/Personal/_packaging/richnav/nuget/v3/index.json'
    isPrivateFeed: true
  continueOnError: true
