# Runs weekly or after every push to all branches to validate indexing against development environment

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
queue:
  name: Hosted VS2017
  timeoutInMinutes: 60

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- task: MS-RichCodeNav.Indexer.build-task.RichCodeNavIndexer@0
  displayName: Rich Code Navigation Upload to Development
  inputs:
    languages: 'typescript'
    githubServiceConnection: 'noellelc'
    environment: development
  continueOnError: true
